# Đăng nhậpf bằng google

```mermaid



sequenceDiagram
    Người dùng->>+Hộp thoại tìm kiếm sản phẩm: Người dùng nhập vào tên sản phẩm và nhấp nút tìm kiếm
    Hộp thoại tìm kiếm sản phẩm ->> APIController: Gửi request với chuỗi tìm kiếm của khách hàng
    APIController ->> APIController: Tìm kiếm các sản phẩm có tên phù hợp với chuỗi
    APIController -->> Hộp thoại tìm kiếm sản phẩm: Trả về kết quả
    alt products
    Hộp thoại tìm kiếm sản phẩm --> Người dùng: Hiển thị ra tất cả tìm được
    else null
    Hộp thoại tìm kiếm sản phẩm --> Người dùng: Hiển thị không tìm thấy sản phẩm
end

    



```
