
sequenceDiagram
    Trang quản lý nhân viên ->> Form tạo nhân viên: Hiển thị form tạo nhân viên
    Admin ->> Form tạo nhân viên: Người dùng nhập vào các thông tin cần thiết và nhấn tạo.
    Form tạo nhân viên  ->> Trình duyệt: Lấy biến admin có trong session storage
    Trình duyệt -->> Form tạo nhân viên : Trả về biến admin
    Trang quản lý nhân viên ->> APIController: Gửi lên token kèm với thông tin của nhân viên mới lên API
    APIController ->> APIController: Xác nhận token và thông tin nhân viên
    alt token sai
    APIController -->> Form tạo nhân viên: Trả kết quả sai token
    Form tạo nhân viên ->> Admin: Hiển thị thông báo yêu cầu đăng nhập lại
    end
    APIController ->> APIController: Tạo nhân viên mới
    APIController -->> Form tạo nhân viên: Trả kết quả thành công
    Form tạo nhân viên ->> Trang quản lý nhân viên: Hiển thị lại list nhân viên
