
sequenceDiagram
    Nhân viên ->> Trang chủ admin: Nhân viên nhấp chọn quản lý sản phẩm trên side menu
    Trang chủ admin ->> Trang quản lý sản phẩm: Hiển thị trang quản lý sản phẩm
    Trang quản lý sản phẩm ->> Trình duyệt: Lấy biến admin có trong session storage
    Trình duyệt -->> Trang quản lý sản phẩm: Trả về biến admin
    Trang quản lý sản phẩm ->> APIController: Gửi lên token từ biến admin lên API
    APIController ->> APIController: Xác nhận token đó
    alt token sai
    APIController -->> Trang quản lý sản phẩm: Trả kết quả sai token
   Trang quản lý sản phẩm ->> Nhân viên: Hiển thị thông báo yêu cầu đăng nhập lại
    end
    APIController -->> Trang quản lý sản phẩm: Trả kết quả thành công kèm với list các sản phẩm
    Trang quản lý sản phẩm ->> Nhân viên: Hiển thị các sản phẩm có từ kết quả trả về

