@host= https://localhost:7206

POST {{host}}/collections
Content-Type: application/json

{
    "categoryName": "Food",
    "products":[
        {
            "productName":"Banana Flavor",
            "productDetail":"This food have flavor is Banana",
            "productQuantity": 65,
            "productPrice": 120000,
            "imageData":"./../../pet_store_backend/image/1.png"
        },
        {
            "productName":"Chocolate Flavor",
            "productDetail":"This food have flavor is Banana",
            "productQuantity": 100,
            "productPrice": 150000,
            "imageData":"./../../pet_store_backend/image/2.png"
        }
    ]
}