@host= https://localhost:7206

GET {{host}}/dinners
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI5ZjlkOWQzMC1lNjNhLTQ5YTMtYjQ1My1jODNiN2MzMzE1NmQiLCJnaXZlbl9uYW1lIjoiRGFuZyBOZ3V5ZW4gVGhpZW4iLCJmYW1pbHlfbmFtZSI6IkRhdCIsImp0aSI6IjlmOWQ5ZDMwLWU2M2EtNDlhMy1iNDUzLWM4M2I3YzMzMTU2ZCIsImV4cCI6MTY5Nzk1MzkwMCwiaXNzIjoiUGV0X1N0b3JlIiwiYXVkIjoiUGV0X1N0b3JlIn0.Exvctc1SMDPMV5OQUdfFt5kDZ5fhJlTeBYWm9hbvqf0