@host= https://localhost:7206

GET {{host}}/dinners
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZmUyYWFmOC05NTJhLTRhOTUtOGE4MS0xZWFiMGQ1MTk0ZmYiLCJnaXZlbl9uYW1lIjoiRGF0IiwiZmFtaWx5X25hbWUiOiJUaGllbiIsImp0aSI6ImFmZTJhYWY4LTk1MmEtNGE5NS04YTgxLTFlYWIwZDUxOTRmZiIsIlRhYmxlTmFtZSI6WyJVc2VyUm9sZXMiLCJVc2VyUGVybWlzc2lvbnMiLCJVc2VycyIsIlByb2R1Y3RzIiwiQ2F0ZWdvcmllcyJdLCJSZWFkIjpbIlRydWUiLCJUcnVlIiwiVHJ1ZSIsIlRydWUiLCJUcnVlIl0sIkNyZWF0ZSI6WyJUcnVlIiwiVHJ1ZSIsIlRydWUiLCJUcnVlIiwiVHJ1ZSJdLCJVcGRhdGUiOlsiVHJ1ZSIsIlRydWUiLCJUcnVlIiwiVHJ1ZSIsIlRydWUiXSwiRGVhY3RpdmF0ZSI6WyJUcnVlIiwiVHJ1ZSIsIlRydWUiLCJUcnVlIiwiVHJ1ZSJdLCJleHAiOjE3MDA4MzQxOTEsImlzcyI6IlBldF9TdG9yZSIsImF1ZCI6IlBldF9TdG9yZSJ9.PppkKJSgMGmWOK9VP6c0cpfM-yMyoYQ8WQswsj6vMyk