# Đăng nhậpf bằng email và mật khẩu

```mermaid

sequenceDiagram
    Alice->>+John: Đăng nhập google gì đo
    Alice->>+John: John, can you hear me?
    John-->>-Alice: Hi Alice, I can hear you!
    John-->>-Alice: I feel great!

```
