# Xóa sản phẩm trong giỏ hàng

```mermaid
sequenceDiagram
    Người dùng->>+Trang check out: Người dùng chọn item cần được xóa khỏi cart
    Trang check out ->> Trình duyệt: Lấy biến user có trong local storage
    Trình duyệt -->> Trang check out: Trả về biến user
    Trang check out ->> APIController: Gửi token từ biến user kèm với id của sản phẩm cần xóa
    APIController ->> APIController: Xác minh token
    alt token sai
    APIController -->> Trang check out: Trả kết quả sai token
    Trang check out ->> Người dùng: Hiển thị thông báo yêu cầu đăng nhập lại
    end
    APIController -->> APIController: Tiến hành xóa sản phẩm ra khỏi cart
    APIController -->> Trang check out: Thông báo kết quả thành công
    Trang check out ->> Người dùng: Tái hiển thị lại cart
```